apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-static-web
  labels:
    app: {{ .Chart.Name }}
    role: myrole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        role: myrole
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - name: web-nginx
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: config
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx
          readinessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
        - name: apache
          image: {{ .Values.apache.image }}
          ports:
            - name: web-apache
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: nginx